version: '3'

services:
  mcp-feishu-proj:
    image: python:3.9-slim  # 或其他包含基本shell工具的镜像
    command: sh -c "pip install uv && uv tool run /app --transport sse"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    environment:
      - SSE_SERVER_HOST=${SSE_SERVER_HOST}
      - SSE_SERVER_PORT=${SSE_SERVER_PORT}
      - FS_PROJ_BASE_URL=${FS_PROJ_BASE_URL}
      - FS_PROJ_PROJECT_KEY=${FS_PROJ_PROJECT_KEY}
      - FS_PROJ_USER_KEY=${FS_PROJ_USER_KEY}
      - FS_PROJ_PLUGIN_ID=${FS_PROJ_PLUGIN_ID}
      - FS_PROJ_PLUGIN_SECRET=${FS_PROJ_PLUGIN_SECRET}
    ports:
      - "8000:8000"
    restart: unless-stopped
