name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: unitest
    
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        if [ -f requirements.txt ]; then uv pip sync requirements.txt; fi
        uv pip install -e .
    
    - name: Set up environment variables
      run: |
        echo "FS_PROJ_BASE_URL=${{ vars.FS_PROJ_BASE_URL }}" >> $GITHUB_ENV
        echo "FS_PROJ_PROJECT_KEY=${{ vars.FS_PROJ_PROJECT_KEY }}" >> $GITHUB_ENV
        echo "FS_PROJ_USER_KEY=${{ vars.FS_PROJ_USER_KEY }}" >> $GITHUB_ENV
        echo "FS_PROJ_PLUGIN_ID=${{ vars.FS_PROJ_PLUGIN_ID }}" >> $GITHUB_ENV
        echo "FS_PROJ_PLUGIN_SECRET=${{ secrets.FS_PROJ_PLUGIN_SECRET }}" >> $GITHUB_ENV
    
    - name: Run tests
      run: |
        python -m unittest discover -s src/mcp_server -p "test_*.py"
